baseURL = 'https://ralfnetto.me/'
languageCode = 'en-us'
title = 'Blog'
theme = 'hugo-blog-awesome'

[[params.socialIcons]]
name = "github"
url = "https://github.com/ralfnetto"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/ralfnetto"
